node {
  node_id: "//update_python_with_ai/guides:coverage"
  reverse_dependencies: "//testing/specs:agent_conversation_history_impl_coverage"
  reverse_dependencies: "//testing/specs:agent_loop_guard_impl_coverage"
  reverse_dependencies: "//testing/specs:agent_node_cleaner_impl_coverage"
  reverse_dependencies: "//testing/specs:agent_runner_impl_coverage"
  reverse_dependencies: "//testing/specs:bazel_graph_storage_impl_coverage"
  reverse_dependencies: "//testing/specs:bazel_manifest_loader_impl_coverage"
  reverse_dependencies: "//testing/specs:bazel_model_config_impl_coverage"
  reverse_dependencies: "//testing/specs:bazel_node_config_impl_coverage"
  reverse_dependencies: "//testing/specs:bazel_node_id_utils_impl_coverage"
  reverse_dependencies: "//testing/specs:bazel_runner_impl_coverage"
  reverse_dependencies: "//testing/specs:dag_cleaner_impl_coverage"
  reverse_dependencies: "//testing/specs:file_paths_impl_coverage"
  reverse_dependencies: "//testing/specs:runner_logger_impl_coverage"
  reverse_dependencies: "//testing/specs:sandbox_file_editor_impl_coverage"
  reverse_dependencies: "//testing/specs:sandbox_file_reader_impl_coverage"
  reverse_dependencies: "//testing/specs:sandbox_guide_delivery_impl_coverage"
  reverse_dependencies: "//testing/specs:sandbox_impl_coverage"
  reverse_dependencies: "//testing/specs:sandbox_run_control_impl_coverage"
  reverse_dependencies: "//testing/specs:template_format_impl_coverage"
  reverse_dependencies: "//testing/specs:tool_provider_impl_coverage"
}
node {
  node_id: "//update_python_with_ai/guides:grounding_to_lib"
  reverse_dependencies: "//testing/specs:bazel_graph_storage_impl_lib"
  reverse_dependencies: "//testing/specs:bazel_target_labels_ext_lib"
  reverse_dependencies: "//testing/specs:commonmark_ext_lib"
  reverse_dependencies: "//testing/specs:dag_cleaner_impl_lib"
  reverse_dependencies: "//testing/specs:file_paths_impl_lib"
  reverse_dependencies: "//testing/specs:filesystem_ext_lib"
  reverse_dependencies: "//testing/specs:json_manifest_ext_lib"
  reverse_dependencies: "//testing/specs:model_config_ext_lib"
  reverse_dependencies: "//testing/specs:openai_ext_lib"
  reverse_dependencies: "//testing/specs:runner_logger_impl_lib"
  reverse_dependencies: "//testing/specs:sandbox_file_reader_impl_lib"
  reverse_dependencies: "//testing/specs:sandbox_guide_delivery_impl_lib"
  reverse_dependencies: "//testing/specs:template_format_impl_lib"
  reverse_dependencies: "//testing/specs:update_with_ai_proto_ext_lib"
}
node {
  node_id: "//update_python_with_ai/guides:grounding_to_test"
  reverse_dependencies: "//testing/specs:agent_conversation_history_impl_test"
  reverse_dependencies: "//testing/specs:agent_loop_guard_impl_test"
  reverse_dependencies: "//testing/specs:agent_node_cleaner_impl_test"
  reverse_dependencies: "//testing/specs:agent_runner_impl_test"
  reverse_dependencies: "//testing/specs:bazel_graph_storage_impl_test"
  reverse_dependencies: "//testing/specs:bazel_manifest_loader_impl_test"
  reverse_dependencies: "//testing/specs:bazel_node_config_impl_test"
  reverse_dependencies: "//testing/specs:bazel_runner_impl_test"
  reverse_dependencies: "//testing/specs:dag_cleaner_impl_test"
  reverse_dependencies: "//testing/specs:file_paths_impl_test"
  reverse_dependencies: "//testing/specs:sandbox_change_summary_validator_impl_test"
  reverse_dependencies: "//testing/specs:sandbox_file_editor_impl_test"
  reverse_dependencies: "//testing/specs:sandbox_file_reader_impl_test"
  reverse_dependencies: "//testing/specs:sandbox_guide_delivery_impl_test"
  reverse_dependencies: "//testing/specs:template_format_impl_test"
}
node {
  node_id: "//update_python_with_ai/guides:qa"
  reverse_dependencies: "//testing/specs:agent_conversation_history_impl_qa"
  reverse_dependencies: "//testing/specs:agent_loop_guard_impl_qa"
  reverse_dependencies: "//testing/specs:agent_node_cleaner_impl_qa"
  reverse_dependencies: "//testing/specs:agent_runner_impl_qa"
  reverse_dependencies: "//testing/specs:bazel_graph_storage_impl_qa"
  reverse_dependencies: "//testing/specs:bazel_manifest_loader_impl_qa"
  reverse_dependencies: "//testing/specs:bazel_model_config_impl_qa"
  reverse_dependencies: "//testing/specs:bazel_node_config_impl_qa"
  reverse_dependencies: "//testing/specs:bazel_node_id_utils_impl_qa"
  reverse_dependencies: "//testing/specs:bazel_runner_impl_qa"
  reverse_dependencies: "//testing/specs:dag_cleaner_impl_qa"
  reverse_dependencies: "//testing/specs:file_paths_impl_qa"
  reverse_dependencies: "//testing/specs:runner_logger_impl_qa"
  reverse_dependencies: "//testing/specs:sandbox_change_summary_validator_impl_qa"
  reverse_dependencies: "//testing/specs:sandbox_file_editor_impl_qa"
  reverse_dependencies: "//testing/specs:sandbox_file_reader_impl_qa"
  reverse_dependencies: "//testing/specs:sandbox_guide_delivery_impl_qa"
  reverse_dependencies: "//testing/specs:sandbox_impl_qa"
  reverse_dependencies: "//testing/specs:sandbox_run_control_impl_qa"
  reverse_dependencies: "//testing/specs:template_format_impl_qa"
  reverse_dependencies: "//testing/specs:tool_provider_impl_qa"
}
