nodes {
  label: "//update_python_with_ai/guides:high_level_spec"
  known_reverse_dependencies: "//testing/specs:agent_loop_config_high"
  known_reverse_dependencies: "//testing/specs:agent_loop_high"
  known_reverse_dependencies: "//testing/specs:agent_loop_impl_high"
  known_reverse_dependencies: "//testing/specs:agent_node_clean_logic_impl_high"
  known_reverse_dependencies: "//testing/specs:agent_node_tool_executor_high"
  known_reverse_dependencies: "//testing/specs:agent_node_tool_executor_impl_high"
  known_reverse_dependencies: "//testing/specs:bazel_target_labels_ext_high"
  known_reverse_dependencies: "//testing/specs:build_agent_config_high"
  known_reverse_dependencies: "//testing/specs:build_agent_config_impl_high"
  known_reverse_dependencies: "//testing/specs:build_graph_storage_high"
  known_reverse_dependencies: "//testing/specs:build_graph_storage_impl_high"
  known_reverse_dependencies: "//testing/specs:build_message_store_high"
  known_reverse_dependencies: "//testing/specs:build_message_store_impl_high"
  known_reverse_dependencies: "//testing/specs:build_node_loader_high"
  known_reverse_dependencies: "//testing/specs:build_runner_high"
  known_reverse_dependencies: "//testing/specs:build_runner_impl_high"
  known_reverse_dependencies: "//testing/specs:change_summary_validator_high"
  known_reverse_dependencies: "//testing/specs:change_summary_validator_impl_high"
  known_reverse_dependencies: "//testing/specs:conversation_history_high"
  known_reverse_dependencies: "//testing/specs:conversation_history_impl_high"
  known_reverse_dependencies: "//testing/specs:dag_clean_logic_high"
  known_reverse_dependencies: "//testing/specs:dag_cleaner_high"
  known_reverse_dependencies: "//testing/specs:dag_cleaner_impl_high"
  known_reverse_dependencies: "//testing/specs:dag_storage_high"
  known_reverse_dependencies: "//testing/specs:file_editor_high"
  known_reverse_dependencies: "//testing/specs:file_editor_impl_high"
  known_reverse_dependencies: "//testing/specs:file_reader_high"
  known_reverse_dependencies: "//testing/specs:file_reader_impl_high"
  known_reverse_dependencies: "//testing/specs:guide_delivery_high"
  known_reverse_dependencies: "//testing/specs:guide_delivery_impl_high"
  known_reverse_dependencies: "//testing/specs:loop_guard_high"
  known_reverse_dependencies: "//testing/specs:loop_guard_impl_high"
  known_reverse_dependencies: "//testing/specs:manifest_node_loader_high"
  known_reverse_dependencies: "//testing/specs:manifest_node_loader_impl_high"
  known_reverse_dependencies: "//testing/specs:openai_ext_high"
  known_reverse_dependencies: "//testing/specs:run_control_high"
  known_reverse_dependencies: "//testing/specs:run_control_impl_high"
  known_reverse_dependencies: "//testing/specs:runner_logger_high"
  known_reverse_dependencies: "//testing/specs:runner_logger_impl_high"
  known_reverse_dependencies: "//testing/specs:sandbox_high"
  known_reverse_dependencies: "//testing/specs:sandbox_impl_high"
  known_reverse_dependencies: "//testing/specs:tool_provider_high"
  known_reverse_dependencies: "//update_python_with_ai/guides:high_to_low"
}
nodes {
  label: "//update_python_with_ai/guides:high_to_low"
  known_reverse_dependencies: "//testing/specs:agent_loop_config_low"
  known_reverse_dependencies: "//testing/specs:agent_loop_impl_low"
  known_reverse_dependencies: "//testing/specs:agent_loop_low"
  known_reverse_dependencies: "//testing/specs:agent_node_clean_logic_impl_low"
  known_reverse_dependencies: "//testing/specs:agent_node_tool_executor_impl_low"
  known_reverse_dependencies: "//testing/specs:agent_node_tool_executor_low"
  known_reverse_dependencies: "//testing/specs:bazel_target_labels_ext_low"
  known_reverse_dependencies: "//testing/specs:build_agent_config_impl_low"
  known_reverse_dependencies: "//testing/specs:build_agent_config_low"
  known_reverse_dependencies: "//testing/specs:build_graph_storage_impl_low"
  known_reverse_dependencies: "//testing/specs:build_graph_storage_low"
  known_reverse_dependencies: "//testing/specs:build_message_store_impl_low"
  known_reverse_dependencies: "//testing/specs:build_message_store_low"
  known_reverse_dependencies: "//testing/specs:build_node_loader_low"
  known_reverse_dependencies: "//testing/specs:build_runner_impl_low"
  known_reverse_dependencies: "//testing/specs:build_runner_low"
  known_reverse_dependencies: "//testing/specs:change_summary_validator_impl_low"
  known_reverse_dependencies: "//testing/specs:change_summary_validator_low"
  known_reverse_dependencies: "//testing/specs:conversation_history_impl_low"
  known_reverse_dependencies: "//testing/specs:conversation_history_low"
  known_reverse_dependencies: "//testing/specs:dag_clean_logic_low"
  known_reverse_dependencies: "//testing/specs:dag_cleaner_impl_low"
  known_reverse_dependencies: "//testing/specs:dag_cleaner_low"
  known_reverse_dependencies: "//testing/specs:dag_storage_low"
  known_reverse_dependencies: "//testing/specs:file_editor_impl_low"
  known_reverse_dependencies: "//testing/specs:file_editor_low"
  known_reverse_dependencies: "//testing/specs:file_reader_impl_low"
  known_reverse_dependencies: "//testing/specs:file_reader_low"
  known_reverse_dependencies: "//testing/specs:guide_delivery_impl_low"
  known_reverse_dependencies: "//testing/specs:guide_delivery_low"
  known_reverse_dependencies: "//testing/specs:loop_guard_impl_low"
  known_reverse_dependencies: "//testing/specs:loop_guard_low"
  known_reverse_dependencies: "//testing/specs:manifest_node_loader_impl_low"
  known_reverse_dependencies: "//testing/specs:manifest_node_loader_low"
  known_reverse_dependencies: "//testing/specs:openai_ext_low"
  known_reverse_dependencies: "//testing/specs:run_control_impl_low"
  known_reverse_dependencies: "//testing/specs:run_control_low"
  known_reverse_dependencies: "//testing/specs:runner_logger_impl_low"
  known_reverse_dependencies: "//testing/specs:runner_logger_low"
  known_reverse_dependencies: "//testing/specs:sandbox_impl_low"
  known_reverse_dependencies: "//testing/specs:sandbox_low"
  known_reverse_dependencies: "//testing/specs:tool_provider_low"
  known_reverse_dependencies: "//update_python_with_ai/guides:low_to_lib"
  known_reverse_dependencies: "//update_python_with_ai/guides:low_to_test"
}
nodes {
  label: "//update_python_with_ai/guides:low_to_lib"
  known_reverse_dependencies: "//testing/specs:agent_loop_config_lib"
  known_reverse_dependencies: "//testing/specs:agent_loop_impl_lib"
  known_reverse_dependencies: "//testing/specs:agent_loop_lib"
  known_reverse_dependencies: "//testing/specs:agent_node_clean_logic_impl_lib"
  known_reverse_dependencies: "//testing/specs:agent_node_tool_executor_impl_lib"
  known_reverse_dependencies: "//testing/specs:agent_node_tool_executor_lib"
  known_reverse_dependencies: "//testing/specs:bazel_target_labels_ext_lib"
  known_reverse_dependencies: "//testing/specs:build_agent_config_impl_lib"
  known_reverse_dependencies: "//testing/specs:build_agent_config_lib"
  known_reverse_dependencies: "//testing/specs:build_graph_storage_impl_lib"
  known_reverse_dependencies: "//testing/specs:build_graph_storage_lib"
  known_reverse_dependencies: "//testing/specs:build_message_store_impl_lib"
  known_reverse_dependencies: "//testing/specs:build_message_store_lib"
  known_reverse_dependencies: "//testing/specs:build_node_loader_lib"
  known_reverse_dependencies: "//testing/specs:build_runner_impl_lib"
  known_reverse_dependencies: "//testing/specs:build_runner_lib"
  known_reverse_dependencies: "//testing/specs:change_summary_validator_impl_lib"
  known_reverse_dependencies: "//testing/specs:change_summary_validator_lib"
  known_reverse_dependencies: "//testing/specs:conversation_history_impl_lib"
  known_reverse_dependencies: "//testing/specs:conversation_history_lib"
  known_reverse_dependencies: "//testing/specs:dag_clean_logic_lib"
  known_reverse_dependencies: "//testing/specs:dag_cleaner_impl_lib"
  known_reverse_dependencies: "//testing/specs:dag_cleaner_lib"
  known_reverse_dependencies: "//testing/specs:dag_storage_lib"
  known_reverse_dependencies: "//testing/specs:file_editor_impl_lib"
  known_reverse_dependencies: "//testing/specs:file_editor_lib"
  known_reverse_dependencies: "//testing/specs:file_reader_impl_lib"
  known_reverse_dependencies: "//testing/specs:file_reader_lib"
  known_reverse_dependencies: "//testing/specs:guide_delivery_impl_lib"
  known_reverse_dependencies: "//testing/specs:guide_delivery_lib"
  known_reverse_dependencies: "//testing/specs:loop_guard_impl_lib"
  known_reverse_dependencies: "//testing/specs:loop_guard_lib"
  known_reverse_dependencies: "//testing/specs:manifest_node_loader_impl_lib"
  known_reverse_dependencies: "//testing/specs:manifest_node_loader_lib"
  known_reverse_dependencies: "//testing/specs:openai_ext_lib"
  known_reverse_dependencies: "//testing/specs:run_control_impl_lib"
  known_reverse_dependencies: "//testing/specs:run_control_lib"
  known_reverse_dependencies: "//testing/specs:runner_logger_impl_lib"
  known_reverse_dependencies: "//testing/specs:runner_logger_lib"
  known_reverse_dependencies: "//testing/specs:sandbox_impl_lib"
  known_reverse_dependencies: "//testing/specs:sandbox_lib"
  known_reverse_dependencies: "//testing/specs:tool_provider_lib"
}
nodes {
  label: "//update_python_with_ai/guides:low_to_test"
  known_reverse_dependencies: "//testing/specs:agent_loop_impl_test"
  known_reverse_dependencies: "//testing/specs:agent_node_clean_logic_impl_test"
  known_reverse_dependencies: "//testing/specs:agent_node_tool_executor_impl_test"
  known_reverse_dependencies: "//testing/specs:build_agent_config_impl_test"
  known_reverse_dependencies: "//testing/specs:build_graph_storage_impl_test"
  known_reverse_dependencies: "//testing/specs:build_message_store_impl_test"
  known_reverse_dependencies: "//testing/specs:build_runner_impl_test"
  known_reverse_dependencies: "//testing/specs:change_summary_validator_impl_test"
  known_reverse_dependencies: "//testing/specs:conversation_history_impl_test"
  known_reverse_dependencies: "//testing/specs:dag_cleaner_impl_test"
  known_reverse_dependencies: "//testing/specs:file_editor_impl_test"
  known_reverse_dependencies: "//testing/specs:file_reader_impl_test"
  known_reverse_dependencies: "//testing/specs:guide_delivery_impl_test"
  known_reverse_dependencies: "//testing/specs:loop_guard_impl_test"
  known_reverse_dependencies: "//testing/specs:manifest_node_loader_impl_test"
  known_reverse_dependencies: "//testing/specs:run_control_impl_test"
  known_reverse_dependencies: "//testing/specs:runner_logger_impl_test"
  known_reverse_dependencies: "//testing/specs:sandbox_impl_test"
}
nodes {
  label: "//update_python_with_ai/guides:qa"
  known_reverse_dependencies: "//testing/specs:agent_loop_impl_qa"
  known_reverse_dependencies: "//testing/specs:agent_node_clean_logic_impl_qa"
  known_reverse_dependencies: "//testing/specs:agent_node_tool_executor_impl_qa"
  known_reverse_dependencies: "//testing/specs:build_agent_config_impl_qa"
  known_reverse_dependencies: "//testing/specs:build_graph_storage_impl_qa"
  known_reverse_dependencies: "//testing/specs:build_message_store_impl_qa"
  known_reverse_dependencies: "//testing/specs:build_runner_impl_qa"
  known_reverse_dependencies: "//testing/specs:change_summary_validator_impl_qa"
  known_reverse_dependencies: "//testing/specs:conversation_history_impl_qa"
  known_reverse_dependencies: "//testing/specs:dag_cleaner_impl_qa"
  known_reverse_dependencies: "//testing/specs:file_editor_impl_qa"
  known_reverse_dependencies: "//testing/specs:file_reader_impl_qa"
  known_reverse_dependencies: "//testing/specs:guide_delivery_impl_qa"
  known_reverse_dependencies: "//testing/specs:loop_guard_impl_qa"
  known_reverse_dependencies: "//testing/specs:manifest_node_loader_impl_qa"
  known_reverse_dependencies: "//testing/specs:run_control_impl_qa"
  known_reverse_dependencies: "//testing/specs:runner_logger_impl_qa"
  known_reverse_dependencies: "//testing/specs:sandbox_impl_qa"
}
