load("//update_with_ai/support/lib:guides.bzl", "update_guide_with_ai")

update_guide_with_ai(
    name = "high_level_spec",
    src = "high_level_spec.md",
    display_name = "high-level specification guide",
    deps = [],
)

update_guide_with_ai(
    name = "high_to_planning",
    src = "high_to_planning.md",
    display_name = "high-level to planning canvas specification guide",
    deps = [],
)

update_guide_with_ai(
    name = "planning_to_low",
    src = "planning_to_low.md",
    display_name = "planning canvas to low-level specification guide",
    deps = [],
)

update_guide_with_ai(
    name = "low_to_lib",
    src = "low_to_lib.md",
    display_name = "low-level to library code guide",
    deps = [],
)

update_guide_with_ai(
    name = "low_to_test",
    src = "low_to_test.md",
    display_name = "low-level to unit test guide",
    deps = [],
)

update_guide_with_ai(
    name = "qa",
    src = "qa.md",
    display_name = "qa arbiter guide",
    deps = [],
)

update_guide_with_ai(
    name = "spec_qa",
    src = "spec_qa.md",
    display_name = "specification qa arbiter guide",
    deps = [],
)

update_guide_with_ai(
    name = "low_qa",
    src = "low_qa.md",
    display_name = "low-level specification qa arbiter guide",
    deps = [],
)

update_guide_with_ai(
    name = "coverage",
    src = "coverage.md",
    display_name = "coverage arbiter guide",
    deps = [],
)

