load("//update_with_ai/support/lib:guides.bzl", "update_guide_with_ai")

update_guide_with_ai(
    name = "high_level_spec",
    src = "high_level_spec.md",
    display_name = "high-level specification guide",
    deps = [],
)

update_guide_with_ai(
    name = "high_to_grounding",
    src = "high_to_grounding.md",
    display_name = "high-level to grounding specification guide",
    deps = [],
)

update_guide_with_ai(
    name = "grounding_to_lib",
    src = "grounding_to_lib.md",
    display_name = "grounding to library code guide",
    deps = [],
)

update_guide_with_ai(
    name = "grounding_to_test",
    src = "grounding_to_test.md",
    display_name = "grounding to unit test guide",
    deps = [],
)

update_guide_with_ai(
    name = "qa",
    src = "qa.md",
    display_name = "qa arbiter guide",
    deps = [],
)

update_guide_with_ai(
    name = "coverage",
    src = "coverage.md",
    display_name = "coverage arbiter guide",
    deps = [],
)

