"""
Starlark rule for declarative agent/model configuration.

Users declare their agent/model configurations as Bazel targets anywhere in
the repository:

    load("//update_with_ai:agent_config.bzl", "agent_config")

    agent_config(
        name = "my_dev_config",
        model = "my-model-name",
        base_url = "http://localhost:8000/v1",
        max_iterations = 100,
        temperature = "0.7",       # float written as a string
        timeout_seconds = "100.0", # float written as a string (attr name avoids Bazel's reserved `timeout`)
        # No api_key attribute: API keys are never stored in Bazel or in
        # version control. api_key_env (optional) names the exact environment
        # variable holding this config's API key, e.g. "OPENAI_API_KEY" for a
        # provider-specific key. Empty (default) means the plain AGENT_API_KEY
        # variable applies at runtime.
        # api_key_env = "OPENAI_API_KEY",
    )

The rule generates:
  - {name}_config.py   — a Python module containing the AGENT_CONFIG dict,
                         imported at runtime by the BazelAgentConfig component
                         (update_with_ai/lib/bazel_agent_config_impl.py)
  - {name}_config.json — the same configuration for non-Python consumers

Discover all configs with:
    bazel query 'kind(agent_config, //...)'

Run a *_clean target with a specific config:
    bazel run //pkg:my_node_clean -- --config //agent_configs:my_dev_config
"""

def _py_literal(value):
    """Format a Starlark value as a Python literal (for the generated module)."""
    t = type(value)
    if t == "string":
        return json.encode(value)
    if t == "NoneType":
        return "None"
    if t == "bool":
        return "True" if value else "False"
    if t == "float":
        # Starlark float stringification is already Python-compatible
        # (e.g. "0.7", "100.0").
        return str(value)
    return str(value)

def _apparent_label(label):
    """Return the apparent (user-facing) label for a main-repo target.

    With bzlmod, str(ctx.label) yields the canonical form (@@//pkg:name);
    users select configs with the apparent form (//pkg:name), so store that.
    """
    s = str(label)
    if s.startswith("@@"):
        s = s[2:]
    elif s.startswith("@") and "//" in s:
        # @repo//pkg:name: configs live in the main repo; drop the repo part.
        s = s[s.index("//"):]
    return s

def _agent_config_impl(ctx):
    """Generate {name}_config.py and {name}_config.json from the attributes."""
    name = ctx.attr.name
    label = _apparent_label(ctx.label)
    max_tokens = ctx.attr.max_tokens if ctx.attr.max_tokens else None  # 0 == unset

    config = {
        "label": label,
        "name": name,
        "model": ctx.attr.model,
        "base_url": ctx.attr.base_url,
        "api_key_env": ctx.attr.api_key_env,
        "max_iterations": ctx.attr.max_iterations,
        "temperature": float(ctx.attr.temperature),
        "timeout": float(ctx.attr.timeout_seconds),
        "max_tokens": max_tokens,
    }

    # Python module: json-encoded strings are valid Python string literals.
    entries = []
    for key in ("label", "name", "model", "base_url", "api_key_env",
                "max_iterations", "temperature", "timeout", "max_tokens"):
        entries.append('    "{}": {},'.format(key, _py_literal(config[key])))

    py_content = "\n".join(
        ['"""Generated by the agent_config rule. Do not edit."""',
         "# Target: {}".format(label),
         "",
         "AGENT_CONFIG = {"] + entries + ["}", ""]
    )

    py = ctx.actions.declare_file(name + "_config.py")
    ctx.actions.write(output = py, content = py_content)

    js = ctx.actions.declare_file(name + "_config.json")
    ctx.actions.write(output = js, content = json.encode(config))

    return [
        DefaultInfo(
            files = depset([py, js]),
            runfiles = ctx.runfiles(files = [py, js]),
        ),
    ]

_agent_config = rule(
    implementation = _agent_config_impl,
    attrs = {
        "model": attr.string(
            mandatory = True,
            doc = "Model identifier passed to the language model API.",
        ),
        "base_url": attr.string(
            mandatory = True,
            doc = "Base URL of the OpenAI-compatible API endpoint.",
        ),
        "api_key_env": attr.string(
            default = "",
            doc = "Exact name of the environment variable holding this config's API key. "
                + "When set, that variable alone supplies the key at runtime (no fallback, "
                + "so a different provider's key is never used). Empty (default) means the "
                + "plain AGENT_API_KEY variable applies.",
        ),
        "max_iterations": attr.int(
            default = 100,
            doc = "Maximum agent-loop iterations per node.",
        ),
        "temperature": attr.string(
            default = "0.0",
            doc = "Sampling temperature (float written as a string, e.g. \"0.7\").",
        ),
        "timeout_seconds": attr.string(
            default = "60.0",
            doc = "Per-request timeout in seconds (float written as a string, e.g. \"100.0\"). "
                + "Note: named timeout_seconds because Bazel reserves the rule attribute name "
                + "\"timeout\"; the generated config key is \"timeout\".",
        ),
        "max_tokens": attr.int(
            default = 0,
            doc = "Maximum tokens per response; 0 means unset (no max_tokens).",
        ),
        # NOTE: there is deliberately NO api_key attribute. API keys are
        # never part of a Bazel target or version control.
    },
)

agent_config = _agent_config
