# update_with_ai/parts/mcp/tests/BUILD.bazel
load("//bin:pyright_library.bzl", "pyright_test")

pyright_test(
    name = "mcp_session_impl_test",
    srcs = ["mcp_session_impl_test.py"],
    deps = [],
    pyright_deps = [
        "//update_python_with_ai/support/lib:lifecycle",
        "//update_with_ai/parts/agent/lib:agent_config",
        "//update_with_ai/parts/agent/lib:agent_node_config",
        "//update_with_ai/parts/agent/lib:agent_session",
        "//update_with_ai/parts/dag/lib:dag_storage",
        "//update_with_ai/parts/dag/lib:dag_subgraph",
        "//update_with_ai/parts/mcp/lib:mcp_session",
        "//update_with_ai/parts/mcp/lib:mcp_session_impl",
    ],
)

pyright_test(
    name = "mcp_gate_impl_test",
    srcs = ["mcp_gate_impl_test.py"],
    deps = [],
    pyright_deps = [
        "//update_python_with_ai/support/lib:lifecycle",
        "//update_with_ai/parts/agent/lib:agent_session",
        "//update_with_ai/parts/mcp/lib:mcp_gate",
        "//update_with_ai/parts/mcp/lib:mcp_gate_impl",
        "//update_with_ai/parts/mcp/lib:mcp_session",
        "//update_with_ai/parts/sandbox/lib:sandbox_file_editor",
        "//update_with_ai/parts/sandbox/lib:sandbox_file_reader",
        "//update_with_ai/parts/sandbox/lib:tool_provider",
    ],
)

pyright_test(
    name = "mcp_cache_arbiter_impl_test",
    srcs = ["mcp_cache_arbiter_impl_test.py"],
    deps = [],
    pyright_deps = [
        "//update_python_with_ai/support/lib:lifecycle",
        "//update_with_ai/parts/dag/lib:dag_storage",
        "//update_with_ai/parts/dag/lib:dag_subgraph",
        "//update_with_ai/parts/mcp/lib:mcp_cache_arbiter",
        "//update_with_ai/parts/mcp/lib:mcp_cache_arbiter_impl",
        "//update_with_ai/parts/mcp/lib:mcp_session",
    ],
)

pyright_test(
    name = "mcp_server_impl_test",
    srcs = ["mcp_server_impl_test.py"],
    deps = [],
    pyright_deps = [
        "//update_python_with_ai/support/lib:lifecycle",
        "//update_with_ai/parts/agent/lib:agent_session",
        "//update_with_ai/parts/mcp/lib:mcp_cache_arbiter",
        "//update_with_ai/parts/mcp/lib:mcp_gate",
        "//update_with_ai/parts/mcp/lib:mcp_server",
        "//update_with_ai/parts/mcp/lib:mcp_server_impl",
        "//update_with_ai/parts/mcp/lib:mcp_session",
        "//update_with_ai/parts/sandbox/lib:tool_provider",
    ],
)
