# update_with_ai/parts/systems/BUILD.bazel

load("//update_python_with_ai/support/lib:update_python_with_ai.bzl", "update_python_with_ai")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "high_specs",
    srcs = glob(["high/*.md"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "grounding_specs",
    srcs = glob(["grounding/*.pyi"]),
    visibility = ["//visibility:public"],
)

update_python_with_ai(
    name = "bazel_openai_loop_asm",
    module_deps = [
        '//update_with_ai/parts/bazel:bazel_asm',
        '//update_with_ai/parts/bazel:bazel_loop_impl',
        '//update_with_ai/parts/bazel:bazel_openai_config_impl',
        '//update_with_ai/parts/core:runner_logger_impl',
        '//update_with_ai/parts/dag:dag_asm',
        '//update_with_ai/parts/loop:loop_asm',
        '//update_with_ai/parts/sandbox:sandbox_asm',
    ],
)
