# --- CLEANROOM METADATA ---
# LAST_CLEANED: 2026-10-07T23:58:18Z
# LAST_CHANGED: 2026-10-05T04:26:30Z
# CHANGE: new file
# CODE_HASH: 9f87ae8e08eb
# LOW_QA_AUDIT: 2026-10-07T23:58:18Z
# --- END CLEANROOM METADATA ---

"""
## External Mechanics & API Documentation

The `model_config_ext` external component specifies the JSON configuration format and discovery paths for model settings generated by `model_config.bzl`. External boundary specifications define no standalone library files; configuration loaders import standard library modules (`os`, `json`, `pathlib`) directly.

**Model Configuration JSON Fields**

- `label`: Canonical Bazel target label string.
- `name`: Target name string.
- `model`: Model identifier string (e.g. `gpt-4o`, `gemini-1.5-pro`).
- `base_url`: Optional API base URL endpoint string.
- `api_key_env`: Environment variable name designated for API key retrieval.
- `timeout`: Request timeout duration in seconds.
- `conversation_limit`: Maximum turn limit for agent conversation.
- `temperature`: Generation temperature float value.
- `max_tokens`: Maximum tokens limit integer.
- `is_step_mode`: Boolean flag indicating step mode guide pacing.
- `is_startup_reads`: Boolean flag indicating whether to perform startup file inspection.
- `inject_followups`: Boolean flag indicating follow-up tool call injection.
- `node_visit_limit`: Maximum visit count per node.
- `batch_size`: Maximum parallel nodes to process.

**Discovery Paths**

1. Runfiles Tree: `$RUNFILES_DIR/<workspace>/<package>/<name>.json`.
2. Build Output Tree: Adjacent output paths relative to `$BUILD_WORKSPACE_DIRECTORY`.
3. Executable Directory: Directory adjacent to the executing binary.

**Credential Resolution**

- Reads designated environment variable named by `api_key_env`.
- Falls back to ambient standard environment variable (e.g. `OPENAI_API_KEY`) if absent.

## Build Dependencies

(none)

## Usage Snippets

### `Loading Model Configuration and Credentials`

```python
import json
import os
from pathlib import Path
from typing import Any, Mapping

def load_model_config(config_path: str) -> Mapping[str, Any]:
    p = Path(config_path)
    if not p.is_file():
        raise FileNotFoundError(f"Model config file not found: {config_path}")
    data = json.loads(p.read_text(encoding="utf-8"))
    env_var = data.get("api_key_env", "OPENAI_API_KEY")
    api_key = os.environ.get(env_var) or os.environ.get("OPENAI_API_KEY", "")
    return {**data, "resolved_api_key": api_key}
```
"""
