# update_with_ai/parts/tools/BUILD.bazel

load("//update_python_with_ai/support/lib:update_python_with_ai.bzl", "update_python_with_ai")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "high_specs",
    srcs = glob(["high/*.md"], allow_empty = True),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "grounding_specs",
    srcs = glob(["grounding/*.gt", "grounding/*.py", "grounding/*.pyi", "low/*.pyi"], allow_empty = True),
    visibility = ["//visibility:public"],
)

update_python_with_ai(
    name = "tool_coverage",
    module_deps = ['//update_with_ai/parts/agent:agent_session'],
)

update_python_with_ai(
    name = "tool_coverage_impl",
    module_deps = ['//update_with_ai/parts/agent:agent_session', ':tool_coverage'],
)

update_python_with_ai(
    name = "tools_asm",
    module_deps = ['//update_with_ai/parts/agent:agent_session', ':tool_coverage', ':tool_coverage_impl'],
)
