# update_with_ai/parts/core/tests/BUILD.bazel

load("//bin:pyright_library.bzl", "pyright_test")
load("//update_python_with_ai/support/lib:build_derived_test.bzl", "build_derived_test")

package(default_visibility = ["//visibility:public"])

pyright_test(
    name = "runner_logger_impl_test",
    srcs = ["runner_logger_impl_test.py"],
    pyright_deps = [
        "//update_python_with_ai/support/lib:lifecycle",
        "//update_with_ai/parts/core/lib:runner_logger",
        "//update_with_ai/parts/core/lib:runner_logger_impl",
    ],
)

pyright_test(
    name = "file_paths_impl_test",
    srcs = ["file_paths_impl_test.py"],
    pyright_deps = [
        "//update_python_with_ai/support/lib:lifecycle",
        "//update_with_ai/parts/core/lib:file_paths",
        "//update_with_ai/parts/core/lib:file_paths_impl",
    ],
)

build_derived_test(
    name = "targets_derived_test",
)

