nodes {
  key: "@@//testing/specs:dag_clean_logic_high"
  value {
    reverse_dependencies: "@@//testing/specs:dag_clean_logic_low"
    reverse_dependencies: "@@//testing/specs:run_control_high"
    reverse_dependencies: "@@//testing/specs:sandbox_high"
  }
}
nodes {
  key: "@@//testing/specs:dag_clean_logic_low"
  value {
    reverse_dependencies: "@@//testing/specs:run_control_low"
    reverse_dependencies: "@@//testing/specs:sandbox_low"
    reverse_dependencies: "@@//testing/specs:dag_clean_logic_lib"
  }
}
nodes {
  key: "@@//testing/specs:dag_storage_high"
  value {
    reverse_dependencies: "@@//testing/specs:dag_storage_low"
    reverse_dependencies: "@@//testing/specs:dag_clean_logic_high"
    reverse_dependencies: "@@//testing/specs:run_control_high"
    reverse_dependencies: "@@//testing/specs:sandbox_high"
  }
}
nodes {
  key: "@@//testing/specs:dag_storage_low"
  value {
    reverse_dependencies: "@@//testing/specs:run_control_low"
    reverse_dependencies: "@@//testing/specs:dag_clean_logic_low"
    reverse_dependencies: "@@//testing/specs:sandbox_low"
    reverse_dependencies: "@@//testing/specs:dag_storage_lib"
  }
}
nodes {
  key: "@@//testing/specs:file_view_high"
  value {
    reverse_dependencies: "@@//testing/specs:file_view_low"
    reverse_dependencies: "@@//testing/specs:run_control_high"
    reverse_dependencies: "@@//testing/specs:sandbox_high"
    reverse_dependencies: "@@//testing/specs:sandbox_impl_high"
  }
}
nodes {
  key: "@@//testing/specs:file_view_low"
  value {
    reverse_dependencies: "@@//testing/specs:sandbox_impl_low"
    reverse_dependencies: "@@//testing/specs:run_control_low"
    reverse_dependencies: "@@//testing/specs:sandbox_low"
    reverse_dependencies: "@@//testing/specs:file_view_lib"
  }
}
nodes {
  key: "@@//testing/specs:guide_delivery_high"
  value {
    reverse_dependencies: "@@//testing/specs:guide_delivery_low"
    reverse_dependencies: "@@//testing/specs:run_control_high"
    reverse_dependencies: "@@//testing/specs:sandbox_high"
    reverse_dependencies: "@@//testing/specs:sandbox_impl_high"
  }
}
nodes {
  key: "@@//testing/specs:guide_delivery_low"
  value {
    reverse_dependencies: "@@//testing/specs:sandbox_impl_low"
    reverse_dependencies: "@@//testing/specs:run_control_low"
    reverse_dependencies: "@@//testing/specs:sandbox_low"
    reverse_dependencies: "@@//testing/specs:guide_delivery_lib"
  }
}
nodes {
  key: "@@//testing/specs:run_control_high"
  value {
    reverse_dependencies: "@@//testing/specs:run_control_low"
    reverse_dependencies: "@@//testing/specs:sandbox_high"
    reverse_dependencies: "@@//testing/specs:sandbox_impl_high"
  }
}
nodes {
  key: "@@//testing/specs:run_control_low"
  value {
    reverse_dependencies: "@@//testing/specs:sandbox_impl_low"
    reverse_dependencies: "@@//testing/specs:sandbox_low"
    reverse_dependencies: "@@//testing/specs:run_control_lib"
  }
}
nodes {
  key: "@@//testing/specs:sandbox_high"
  value {
    reverse_dependencies: "@@//testing/specs:sandbox_low"
    reverse_dependencies: "@@//testing/specs:sandbox_impl_high"
  }
}
nodes {
  key: "@@//testing/specs:sandbox_impl_high"
  value {
    reverse_dependencies: "@@//testing/specs:sandbox_impl_low"
  }
}
nodes {
  key: "@@//testing/specs:sandbox_impl_lib"
  value {
    reverse_dependencies: "@@//testing/specs:sandbox_impl_qa"
  }
}
nodes {
  key: "@@//testing/specs:sandbox_impl_low"
  value {
    reverse_dependencies: "@@//testing/specs:sandbox_impl_qa"
    reverse_dependencies: "@@//testing/specs:sandbox_impl_test"
    reverse_dependencies: "@@//testing/specs:sandbox_impl_lib"
  }
}
nodes {
  key: "@@//testing/specs:sandbox_impl_test"
  value {
    reverse_dependencies: "@@//testing/specs:sandbox_impl_qa"
  }
}
nodes {
  key: "@@//testing/specs:sandbox_low"
  value {
    reverse_dependencies: "@@//testing/specs:sandbox_impl_low"
    reverse_dependencies: "@@//testing/specs:sandbox_lib"
  }
}
nodes {
  key: "@@//testing/specs:tool_provider_high"
  value {
    reverse_dependencies: "@@//testing/specs:tool_provider_low"
    reverse_dependencies: "@@//testing/specs:guide_delivery_high"
    reverse_dependencies: "@@//testing/specs:file_view_high"
    reverse_dependencies: "@@//testing/specs:dag_clean_logic_high"
    reverse_dependencies: "@@//testing/specs:run_control_high"
    reverse_dependencies: "@@//testing/specs:sandbox_high"
  }
}
nodes {
  key: "@@//testing/specs:tool_provider_low"
  value {
    reverse_dependencies: "@@//testing/specs:run_control_low"
    reverse_dependencies: "@@//testing/specs:guide_delivery_low"
    reverse_dependencies: "@@//testing/specs:file_view_low"
    reverse_dependencies: "@@//testing/specs:dag_clean_logic_low"
    reverse_dependencies: "@@//testing/specs:sandbox_low"
    reverse_dependencies: "@@//testing/specs:tool_provider_lib"
  }
}
