nodes {
  key: "@@//testing/specs:agent_loop_high"
  value {
    reverse_dependencies: "@@//testing/specs:agent_loop_low"
    reverse_dependencies: "@@//testing/specs:sandbox_high"
    reverse_dependencies: "@@//testing/specs:sandbox_impl_high"
  }
}
nodes {
  key: "@@//testing/specs:agent_loop_low"
  value {
    reverse_dependencies: "@@//testing/specs:agent_loop_lib"
    reverse_dependencies: "@@//testing/specs:sandbox_low"
    reverse_dependencies: "@@//testing/specs:sandbox_impl_low"
  }
}
nodes {
  key: "@@//testing/specs:dag_clean_logic_high"
  value {
    reverse_dependencies: "@@//testing/specs:dag_clean_logic_low"
    reverse_dependencies: "@@//testing/specs:dag_cleaner_high"
    reverse_dependencies: "@@//testing/specs:dag_cleaner_impl_high"
    reverse_dependencies: "@@//testing/specs:sandbox_high"
    reverse_dependencies: "@@//testing/specs:sandbox_impl_high"
  }
}
nodes {
  key: "@@//testing/specs:dag_clean_logic_low"
  value {
    reverse_dependencies: "@@//testing/specs:dag_cleaner_low"
    reverse_dependencies: "@@//testing/specs:dag_clean_logic_lib"
    reverse_dependencies: "@@//testing/specs:dag_cleaner_impl_low"
    reverse_dependencies: "@@//testing/specs:sandbox_low"
    reverse_dependencies: "@@//testing/specs:sandbox_impl_low"
  }
}
nodes {
  key: "@@//testing/specs:dag_cleaner_high"
  value {
    reverse_dependencies: "@@//testing/specs:dag_cleaner_low"
    reverse_dependencies: "@@//testing/specs:dag_cleaner_impl_high"
  }
}
nodes {
  key: "@@//testing/specs:dag_cleaner_impl_high"
  value {
    reverse_dependencies: "@@//testing/specs:dag_cleaner_impl_low"
  }
}
nodes {
  key: "@@//testing/specs:dag_cleaner_impl_low"
  value {
    reverse_dependencies: "@@//testing/specs:dag_cleaner_impl_lib"
    reverse_dependencies: "@@//testing/specs:dag_cleaner_impl_test"
  }
}
nodes {
  key: "@@//testing/specs:dag_cleaner_low"
  value {
    reverse_dependencies: "@@//testing/specs:dag_cleaner_lib"
    reverse_dependencies: "@@//testing/specs:dag_cleaner_impl_low"
  }
}
nodes {
  key: "@@//testing/specs:dag_storage_high"
  value {
    reverse_dependencies: "@@//testing/specs:dag_storage_low"
    reverse_dependencies: "@@//testing/specs:dag_clean_logic_high"
    reverse_dependencies: "@@//testing/specs:dag_cleaner_high"
    reverse_dependencies: "@@//testing/specs:dag_cleaner_impl_high"
    reverse_dependencies: "@@//testing/specs:sandbox_high"
  }
}
nodes {
  key: "@@//testing/specs:dag_storage_low"
  value {
    reverse_dependencies: "@@//testing/specs:dag_cleaner_low"
    reverse_dependencies: "@@//testing/specs:dag_clean_logic_low"
    reverse_dependencies: "@@//testing/specs:dag_storage_lib"
    reverse_dependencies: "@@//testing/specs:dag_cleaner_impl_low"
    reverse_dependencies: "@@//testing/specs:sandbox_low"
  }
}
nodes {
  key: "@@//testing/specs:sandbox_high"
  value {
    reverse_dependencies: "@@//testing/specs:sandbox_low"
    reverse_dependencies: "@@//testing/specs:sandbox_impl_high"
  }
}
nodes {
  key: "@@//testing/specs:sandbox_impl_high"
  value {
    reverse_dependencies: "@@//testing/specs:sandbox_impl_low"
  }
}
nodes {
  key: "@@//testing/specs:sandbox_impl_lib"
  value {
    reverse_dependencies: "@@//testing/specs:sandbox_impl_qa"
  }
}
nodes {
  key: "@@//testing/specs:sandbox_impl_low"
  value {
    reverse_dependencies: "@@//testing/specs:sandbox_impl_test"
    reverse_dependencies: "@@//testing/specs:sandbox_impl_lib"
    reverse_dependencies: "@@//testing/specs:sandbox_impl_qa"
  }
}
nodes {
  key: "@@//testing/specs:sandbox_impl_qa"
  value {
    messages {
      kind: "change"
      text: "check"
    }
  }
}
nodes {
  key: "@@//testing/specs:sandbox_low"
  value {
    reverse_dependencies: "@@//testing/specs:sandbox_lib"
    reverse_dependencies: "@@//testing/specs:sandbox_impl_low"
  }
}
nodes {
  key: "@@//testing/specs:tool_provider_high"
  value {
    reverse_dependencies: "@@//testing/specs:tool_provider_low"
    reverse_dependencies: "@@//testing/specs:dag_clean_logic_high"
    reverse_dependencies: "@@//testing/specs:agent_loop_high"
    reverse_dependencies: "@@//testing/specs:sandbox_high"
    reverse_dependencies: "@@//testing/specs:sandbox_impl_high"
  }
}
nodes {
  key: "@@//testing/specs:tool_provider_low"
  value {
    reverse_dependencies: "@@//testing/specs:dag_clean_logic_low"
    reverse_dependencies: "@@//testing/specs:tool_provider_lib"
    reverse_dependencies: "@@//testing/specs:agent_loop_low"
    reverse_dependencies: "@@//testing/specs:sandbox_low"
    reverse_dependencies: "@@//testing/specs:sandbox_impl_low"
  }
}
