nodes {
  key: "@@//guides:high_level_spec"
  value {
    reverse_dependencies: "@@//guides:high_to_low"
  }
}
nodes {
  key: "@@//guides:low_level_spec"
  value {
    reverse_dependencies: "@@//guides:high_to_low"
  }
}
