"""
lib/agent_loop.py

Agent Loop Interface - LLS Specification

Defines types and operations for the agent loop component.
"""

from __future__ import annotations

from typing import Any, Callable, Literal, Protocol, Union, List, Dict, Optional, Tuple
from dataclasses import dataclass, field
from .tool_provider import (
    ToolDefinition,
    ToolResult,
    PresentedToolResult,
    Signal,
    Continue,
    TerminateAgentWithSuccess,
    TerminateAgentWithFailure,
    ToolFailure,
    ToolExecutor,
    T_tool,
)

HistoryEntry = Dict[str, Any]
"""
A conversation history entry: the data appended to the conversation (user
prompt, assistant response, tool call, tool result) for a particular turn.
The format is determined by the language model API.
"""

ToolCall = Dict[str, Any]
"""
A tool request from the model:
{
    "id": str,
    "type": "function",
    "function": {
        "name": str,
        "arguments": str  # JSON string of parameter values
    }
}
"""

Usage = Dict[str, int]
"""
Per-request token usage from the language model API:
{
    "prompt_tokens": int,      # Current conversation size (tokens sent in the request)
    "completion_tokens": int,  # Response size (tokens generated by the model)
    "total_tokens": int        # Tokens used for this request (prompt + completion)
}
"""

CumulativeUsage = Dict[str, int]
"""
Cumulative token usage across all API calls in the run:
{
    "prompt_tokens": int,      # Total prompt tokens across all requests
    "completion_tokens": int,  # Total completion tokens across all requests
    "total_tokens": int,       # Total tokens spent across all requests
    "request_count": int       # Number of API calls made
}
"""

AgentResult = Union[
    Tuple[TerminateAgentWithSuccess, List[HistoryEntry]],
    Tuple[TerminateAgentWithFailure[T_tool], List[HistoryEntry]],
    Tuple[str, List[HistoryEntry]],
]
"""
Result of an agent run. There is no free-text final answer: the run completes
only when a tool signals termination or the loop fails.
- (TerminateAgentWithSuccess, history): Tool-initiated successful termination;
  the signal carries the termination result
- (TerminateAgentWithFailure[T_tool], history): Tool-initiated failure
  termination; the signal carries the failure value
- (error, history): Loop failure (agent failure) with error description and
  full history
"""

LogEvent = Literal[
    "message_added",
    "message_stubbed",
    "tool_called",
    "tool_result",
    "api_response",
    "response_truncated",
    "reminder_injected",
    "run_terminated",
    "error",
]
"""
The type of log event being reported:
- message_added: Message appended to the conversation
- message_stubbed: A tool result was stubbed (its content replaced by a
  placeholder because a newer result for the same file or tool
  command superseded it)
- tool_called: Model requested tool execution
- tool_result: Tool execution results received
- api_response: API response received (includes per-request token usage)
- response_truncated: Model response stopped at the generation limit
- reminder_injected: Termination reminder injected into conversation
- run_terminated: Tool signaled termination
- error: Failure occurred
"""

LoggerCallback = Callable[[LogEvent, Dict[str, Any]], None]
"""
Client-provided function invoked during execution for real-time monitoring.

Receives the event type and associated data. If the callback raises an exception,
the component catches it and continues execution.

Event data fields:
- message_added: {"message": HistoryEntry}
- message_stubbed: {"stubbed_message": HistoryEntry, "replacement_message": HistoryEntry}
- tool_called: {"tool_calls": List[ToolCall]}
- tool_result: {"results": List[ToolResult]}
- api_response: {"usage": Usage}
- response_truncated: {"message": HistoryEntry, "usage": Usage}
- reminder_injected: {"message": str}
- run_terminated: {"termination_value": <the termination signal's value>, "usage": Usage, "cumulative_usage": CumulativeUsage, "final_context_size": int}
- error: {"error": str, "usage": Usage | None, "cumulative_usage": CumulativeUsage | None, "last_context_size": int | None}
"""

TerminationReminderGenerator = Callable[[], str]
"""
Client-provided function that generates the termination-reminder message.
When the model stops without signaling termination, a termination reminder
(this generator's message, or a default when none is configured) is provided
and the loop continues; the run completes only via a termination signal or
the iteration limit. The reminder is not triggered by tool failures (see
ToolFailure in tool_provider).
"""

@dataclass
class AgentLoopConfig:
    """Client-supplied configuration for the agent loop: connection and processing parameters, an optional iteration limit, and an optional termination reminder generator."""
    base_url: str
    api_key: str
    model: str
    max_iterations: int = 10
    temperature: float = 0.0
    timeout: float = 60.0
    max_tokens: Optional[int] = None
    termination_reminder_generator: Optional[TerminationReminderGenerator] = None
    continuation_prompt: Optional[str] = None

class AgentLoop(Protocol):
    """
    Interface for the LLS Agent Loop.

    Runs the agent loop to answer a user prompt: completes when a tool
    signals termination, or a failure occurs. There is no free-text final
    answer: when the model stops without signaling termination, a termination
    reminder is provided and the loop continues. Stubbing follows
    tool_provider semantics: a result whose supersedes flag is set replaces
    the earlier non-stubbed result for the same file or tool command with a
    placeholder.
    """

    def run_agent(
        self,
        prompt: str,
        tools: List[ToolDefinition],
        tool_executor: ToolExecutor[T_tool],
        system_prompt: Optional[str] = None,
        session_start_results: Optional[List[PresentedToolResult]] = None,
        logger: Optional[LoggerCallback] = None,
    ) -> AgentResult:
        """
        Run the agent loop to answer a user prompt.

        Completes when a tool signals termination, or a failure occurs. When
        the model stops without signaling termination, a termination reminder
        is provided and the loop continues (there is no final answer).

        Args:
            prompt: The user's question or instruction (may be empty; an empty
                prompt sends no user message).
            tools: List of tool definitions describing available tools to the LLM.
            tool_executor: Per-tool executor (see tool_provider.ToolExecutor):
                called once per tool call with (name, arguments), returning a
                ToolCallOutcome (a sequence of one or more tool results or a
                Signal).
            system_prompt: Static opening section of the conversation context;
                never modified during the run (default: None).
            session_start_results: Optional tool results (PresentedToolResult
                values, each carrying the tool call it is presented with — a
                result the model did not request) (default: None).
            logger: Optional callback for real-time execution monitoring.

        Returns:
            AgentResult: a (signal, history) termination tuple, or an
            (error, history) loop-failure tuple.

        Preconditions:
            - prompt is a string (may be empty)
            - system_prompt when provided is a string
            - tools is a list of valid tool_provider-compatible tool definitions
            - tool_executor is callable and handles all tools in tools
            - tool_executor returns results in the tool_provider format
            - logger if provided is callable accepting (LogEvent, dict) and returning None
            - Component configured with connection params and optional termination_reminder_generator

        Postconditions:
            - On termination, returns (TerminateAgentWithSuccess, history) or
              (TerminateAgentWithFailure[T_tool], history) — the tool-provider
              termination signal paired with the conversation history
            - On error, returns (error, history) (a loop failure); state unchanged
            - Termination values pass through unchanged from the Signal[T_tool] produced by tool_executor
            - Final termination is terminal—no further processing (no API calls, no tool executions)
            - The system prompt is never modified during the run
            - A tool result's content is rendered into the model-visible tool
              message, with the note appended
            - When a tool result's supersedes flag is set, the earlier non-stubbed
              result for the same file or tool command is replaced by a placeholder
            - A result with the supersedes flag unset supersedes nothing; at most one
              earlier result is superseded per result
            - Chronological order maintained
            - No state persists between runs
            - Logger callback invoked after data appended to history
            - If tool_executor returns Continue, the loop continues with the model processing the tool results
            - If tool_executor returns TerminateAgentWithSuccess, the loop stops and
              returns (TerminateAgentWithSuccess, history); TerminateAgentWithFailure[T_tool]
              stops the loop and returns (TerminateAgentWithFailure[T_tool], history)
            - If tool_executor returns ToolFailure[T_tool] (a tool failure — the agent misused a tool
              as specified by the tool provider): the failure message (e.g., the sandbox's reminder
              of what the agent can do) is appended to the conversation and the loop continues with
              the model making its next move. Tool failures are recoverable: no session reset, no
              history clearing, and no agent failure.
            - If tool_executor raises an exception (an unhandled error by the tool_executor): the
              agent_loop catches it and returns (error, history) (state unchanged)

        Failure Handling:
            - Returns (error, history) when:
              - API call fails
              - API returns malformed response
              - Tool executor raises an exception
              - Maximum iterations exceeded
            - State unchanged on failure
            - Logger callback exceptions caught and ignored

        Notes:
            - No state persists between runs.
            - Termination values never inspected, transformed, or interpreted.
            - A loop reminder is provided at most once per run.
            - A result with the supersedes flag set replaces the earlier
              non-stubbed result for the same file or tool command.
            - A tool failure never supersedes an earlier result.
        """
        ...


__all__ = [
    "HistoryEntry",
    "ToolCall",
    "ToolDefinition",
    "ToolResult",
    "Signal",
    "Continue",
    "TerminateAgentWithSuccess",
    "TerminateAgentWithFailure",
    "ToolFailure",
    "ToolExecutor",
    "AgentLoop",
    "Usage",
    "CumulativeUsage",
    "AgentResult",
    "LogEvent",
    "LoggerCallback",
    "TerminationReminderGenerator",
    "AgentLoopConfig",
]
