"""DAG storage model defining nodes, dependencies, and messages."""

from typing import Protocol, TypeAlias, Sequence, Mapping, Any, Optional
from dataclasses import dataclass

NodeId: TypeAlias = str
NodeData: TypeAlias = Mapping[str, Any]
MessageContent: TypeAlias = str


@dataclass(frozen=True)
class DagMessage:
    content: MessageContent
    sender: Optional[NodeId] = None


PendingMessage: TypeAlias = DagMessage


class DagStorage(Protocol):
    def get_dependencies(self, node: NodeId) -> Sequence[NodeId]: ...
    def get_reverse_dependencies(self, node: NodeId) -> Sequence[NodeId]: ...
    def get_pending_messages(self, node: NodeId) -> Sequence[PendingMessage]: ...
    def queue_pending_messages(self, node: NodeId, messages: Sequence[DagMessage]) -> None: ...
    def clear_pending_messages(self, node: NodeId) -> None: ...
    def record_node_data(self, node: NodeId, data: NodeData) -> None: ...
    def get_node_data(self, node: NodeId) -> Optional[NodeData]: ...
    def mark_dirty(self, node: NodeId) -> None: ...
    def is_dirty(self, node: NodeId) -> bool: ...
