# --- CLEANROOM METADATA ---
# LAST_CLEANED: 2026-10-05T20:52:01Z
# LAST_CHANGED: 2026-10-05T04:26:30Z
# CHANGE: new file
# CODE_HASH: 0fa532d5595e
# --- END CLEANROOM METADATA ---

"""
## External Mechanics & API Documentation

The `bazel_manifest_ext` external component specifies the JSON schemas and deserialization mechanics for manifest files generated by the `update_with_ai.bzl` Starlark rules. External boundary specifications define no standalone library files; manifest loaders import Python's standard `json` module directly or use boundary helpers.

**Unit Manifest Schema (`{unit}_unit_manifest.json`)**

Written by the `define_unit` Starlark rule.
- `label`: Canonical Bazel label string of the unit (e.g. `//pkg:target`).
- `name`: Target name string within the package.
- `unit_name`: Alias for `name`.
- `dir`: Package directory path relative to workspace root.
- `unit_dir`: Alias for `dir`.
- `unit_deps`: Sequence of dependency unit label strings.
- `deps`: Alias for `unit_deps`.
- `component_type`: Component classification string (`"implementation"`, `"assembly"`, `"interface"`, or `"external"`).

**Role Manifest Schema (`{role}_role_manifest.json`)**

Written by the `define_role` Starlark rule.
- `label`: Canonical Bazel label string of the role (e.g. `//update_python_with_ai:lib`).
- `name`: Target role name string (e.g. `"lib"`, `"test"`, `"qa"`).
- `role_name`: Alias for `name`.
- `src_pattern`: Format string pattern for the primary source file containing `{unit_dir}` and `{unit_name}` placeholders.
- `template`: Optional relative path to a template file.
- `prompt_template`: Format string pattern for the task prompt containing `{unit_dir}`, `{unit_name}`, `{lib_kind_clause}`, `{component_name}`, and `{component_type}` placeholders.
- `guide`: Optional label string of the guide target.
- `allows_step_mode`: Boolean indicating if progressive step mode is permitted.
- `node_deps`: Sequence of fixed node target label strings specifying direct non-star dependencies for every node with this role.
- `role_deps`: Sequence of role label strings specifying direct role dependencies.
- `silent_role_deps`: Sequence of role label strings specifying non-propagating role dependencies.
- `stub_role_deps`: Sequence of role label strings specifying stub dependencies.
- `star_role_deps`: Sequence of role label strings specifying transitive star-role dependencies.
- `silent_cross_role_deps`: Sequence of role label strings specifying cross-role silent dependencies.
- `feedback_role_deps`: Sequence of role label strings specifying feedback/blame role dependencies.
- `active_component_types`: Sequence of component type strings active for this role.
- `verify_template`: Format string pattern for verification check commands.
- `verification_success_message`: Optional verification success confirmation message.
- `silent_srcs`: Sequence of silent source file pattern strings.

**Monolithic Target Manifest Schema (`{name}_manifest.json`)**

Written by legacy or monolithic `update_with_ai` targets.
- `label`: Canonical Bazel target label string.
- `name`: Target name string within package.
- `prompt`: Optional task prompt string.
- `task_prompt`: Alias for `prompt`.
- `tools`: Sequence of tool target label strings.
- `deps`: Sequence of dependency target label strings.
- `silent_deps`: Sequence of silent dependency target label strings.
- `feedback_deps`: Sequence of feedback dependency target label strings.
- `star_deps`: Sequence of star dependency target label strings.
- `src`: Optional declared primary source file path.
- `template`: Optional template file path string.
- `template_parameters`: Mapping of template placeholder keys to values.
- `guide`: Optional guide target label string.
- `verify`: Optional verification command string.
- `verification_check`: Alias for `verify`.
- `silent_srcs`: Sequence of silent source file path strings.

## Build Dependencies

(none)

## Usage Snippets

### `Deserializing Unit and Role Manifests`

```python
import json
from typing import Any, Mapping

def load_unit_manifest(content: str) -> Mapping[str, Any]:
    \"\"\"Deserializes unit manifest JSON text into a typed mapping.\"\"\"
    data = json.loads(content)
    if "label" not in data or "name" not in data:
        raise ValueError("Invalid unit manifest: missing required fields 'label' or 'name'")
    return data

def load_role_manifest(content: str) -> Mapping[str, Any]:
    \"\"\"Deserializes role manifest JSON text into a typed mapping.\"\"\"
    data = json.loads(content)
    if "label" not in data or "name" not in data:
        raise ValueError("Invalid role manifest: missing required fields 'label' or 'name'")
    return data

def load_target_manifest(content: str) -> Mapping[str, Any]:
    \"\"\"Deserializes monolithic target manifest JSON text into a typed mapping.\"\"\"
    data = json.loads(content)
    if "label" not in data or "name" not in data:
        raise ValueError("Invalid target manifest: missing required fields 'label' or 'name'")
    return data
```
"""
