# update_with_ai/parts/bazel/BUILD.bazel

load("//update_python_with_ai/support/lib:update_python_with_ai.bzl", "update_python_with_ai")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "high_specs",
    srcs = glob(["high/*.md"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "grounding_specs",
    srcs = glob(["grounding/*.pyi"]),
    visibility = ["//visibility:public"],
)

update_python_with_ai(
    name = "bazel_asm",
    module_deps = [':bazel_manifest_loader_impl', ':bazel_node_config_impl', ':bazel_storage_impl', ':bazel_target_impl', '//update_with_ai/parts/core:file_paths_impl'],
)

update_python_with_ai(
    name = "bazel_manifest_loader",
    module_deps = ['//update_with_ai/parts/agent:agent_storage', ':bazel_target', '//update_with_ai/parts/dag:dag_storage', '//update_with_ai/parts/agent:agent_file_alias', '//update_with_ai/parts/agent:agent_node_config'],
)

update_python_with_ai(
    name = "bazel_manifest_loader_impl",
    module_deps = ['//update_with_ai/parts/agent:agent_storage', ':bazel_manifest_loader', ':bazel_target', '//update_with_ai/parts/dag:dag_storage', '//update_with_ai/parts/agent:agent_file_alias', '//update_with_ai/parts/core:json_manifest_ext', '//update_with_ai/parts/agent:agent_node_config'],
)

update_python_with_ai(
    name = "bazel_openai_config_impl",
    module_deps = ['//update_with_ai/parts/agent:agent_config', '//update_with_ai/parts/dag:dag_config', '//update_with_ai/parts/core:model_config_ext', '//update_with_ai/parts/openai:openai_config'],
)

update_python_with_ai(
    name = "bazel_node_config_impl",
    module_deps = ['//update_with_ai/parts/agent:agent_config', '//update_with_ai/parts/agent:agent_file_alias', '//update_with_ai/parts/agent:agent_node_config', '//update_with_ai/parts/agent:agent_session', ':bazel_manifest_loader', '//update_with_ai/parts/dag:dag_storage', '//update_with_ai/parts/core:file_paths', '//update_with_ai/parts/sandbox:tool_provider'],
)

update_python_with_ai(
    name = "bazel_loop_impl",
    module_deps = [':bazel_manifest_loader', '//update_with_ai/parts/core:runner_logger', '//update_with_ai/parts/dag:dag_storage', '//update_with_ai/parts/loop:loop', '//update_with_ai/parts/loop:loop_cleaner', '//update_with_ai/parts/loop:loop_node_cleaner'],
)

update_python_with_ai(
    name = "bazel_storage_impl",
    module_deps = ['//update_with_ai/parts/agent:agent_storage', ':bazel_target', '//update_with_ai/parts/core:file_paths', '//update_with_ai/parts/core:update_with_ai_proto_ext'],
)

update_python_with_ai(
    name = "bazel_target",
    module_deps = ['//update_with_ai/parts/dag:dag_storage', '//update_with_ai/parts/core:file_paths'],
)

update_python_with_ai(
    name = "bazel_target_impl",
    module_deps = [':bazel_target', ':bazel_target_labels_ext', '//update_with_ai/parts/dag:dag_storage', '//update_with_ai/parts/core:file_paths'],
)

update_python_with_ai(
    name = "bazel_target_labels_ext",
    module_deps = [],
)
